language: ruby
bundler_args: --without development production staging development_remote
python:
  - '2.7'
env:
  matrix:
    - SECRET_TOKEN=NhUVfDTMNAUCt5Gt39GKj2w98KQ
  global:
    - secure: e8Mm50pdxH5oDeGCRIBRYhhiwSM1Ly9vdIrWnKhmiepo+5kmxgcH8I+qFxNjLscC0Kw6KTwRpep+hh58Go7DjPrV+9Dca1I4rpLymQGnR71gP6mY3Of5rGpSKm5d89Y4zlvVpB0snNWhSZiQn+AOH8tztSRXnWG/UOOa1JWR90I=
    - secure: Hoc+7DWKaqvq3b1C9WA3IWpJw04GEzIlK0rXPBgtQNr8c6+PJWN/A7hhoLSrzusz2o+s/hL7efdg9q4IkSNtQlaQW+u5OHce7tbgl5uiopBfnGPmlL1tf56xc5ayXUDG3dvV8OWGM/NT+RsTKAZDlKJRVFNPNFA/jiV/zQwimUg=
rvm:
  - 2.0.0
  - ruby-head
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - gem update --system
  - gem --version
  - pip install --user robotframework
  - pip install --user robotframework-selenium2library
services: mongodb
before_script:
  - export SECRET_TOKEN=$(rake secret)
  - RAILS_ENV=test bundle exec rake db:reset
  - rails server -d -e test
script:
  - ~/.local/bin/pybot robot/*.robot
  - bundle exec rake spec cucumber
matrix:
  include:
    - rvm: 2.0.0
      gemfile: Gemfile
    - rvm: ruby-head
      gemfile: gemfiles/2.1.gemfile
