language: ruby
bundler_args: --without development production staging development_remote
python:
  - "2.7"
install:
  - "pip install robotframework"
  - "pip install robotframework-selenium2library"
env:
  - CI=true
rvm:
  - "2.0.0"
services: mongodb
script:
  - pybot robot/*.robot
  - bundle exec rake test
