language: ruby
bundler_args: --without development production staging development_remote
python:
- '2.7'
env:
  matrix:
  - CI=true DISPLAY=:99.0
  global:
  - secure: e8Mm50pdxH5oDeGCRIBRYhhiwSM1Ly9vdIrWnKhmiepo+5kmxgcH8I+qFxNjLscC0Kw6KTwRpep+hh58Go7DjPrV+9Dca1I4rpLymQGnR71gP6mY3Of5rGpSKm5d89Y4zlvVpB0snNWhSZiQn+AOH8tztSRXnWG/UOOa1JWR90I=
  - secure: Hoc+7DWKaqvq3b1C9WA3IWpJw04GEzIlK0rXPBgtQNr8c6+PJWN/A7hhoLSrzusz2o+s/hL7efdg9q4IkSNtQlaQW+u5OHce7tbgl5uiopBfnGPmlL1tf56xc5ayXUDG3dvV8OWGM/NT+RsTKAZDlKJRVFNPNFA/jiV/zQwimUg=
rvm:
- 2.0.0
before_install:
- gem update --system
- gem --version
- pip install --user robotframework
- pip install --user robotframework-selenium2library
services: mongodb
before_script:
- export SECRET_TOKEN=$(rake secret)
- sh -e /etc/init.d/xvfb start
- bundle exec rake db:reset
- bundle exec rails server -d
script:
- ~/.local/bin/pybot robot/*.robot
- bundle exec rake spec cucumber
