<% begin
    credentials = YAML.load_file('config/db.credentials.yml')[ENV['RAILS_ENV']]
    username = credentials['user']
    password = credentials['password']
    port = credentials['port']
    host = credentials['url']
    database = credentials['database']
    ENV['MONGOID_DATABASE'] ||= database
    ENV['MONGOID_PASSWORD'] ||= password
    ENV['MONGOID_USERNAME'] ||= user
    ENV['MONGOID_PORT'] ||= port
    ENV['MONGOID_HOST'] ||= host
  rescue Exception => e
    
  end
    
  
%>

development:
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>

test:
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>

# set these environment variables on your prod server
production:
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>
