<% begin
    credentials = YAML.load_file('config/db.credentials.yml')[ENV['RAILS_ENV']]
    username = credentials['user']
    password = credentials['password']
    port = credentials['port']
    host = credentials['url']
    database = credentials['database']
  rescue Exception => e
    
  end
%>

development:
  username: <%= username %>
  password: <%= password %>
  port: <%= port %>
  host: <%= host %>
  database: <%= database %>

test:
  username: <%= username %>
  password: <%= password %>
  port: <%= port %>
  host: <%= host %>
  database: <%= database %>

# set these environment variables on your prod server
production:
  host: <%= host || ENV['MONGOID_HOST'] %>
  port: <%= port || ENV['MONGOID_PORT'] %>
  username: <%= username || ENV['MONGOID_USERNAME'] %>
  password: <%= password || ENV['MONGOID_PASSWORD'] %>
  database: <%= database || ENV['MONGOID_DATABASE'] %>
